num_vms = 3

Vagrant.configure("2") do |config|
  (1..num_vms).each do |i|
    config.vm.define "zookeeper-#{i}" do |node|
      node.vm.box = "ubuntu-focal"
      node.vm.network "private_network", ip: "192.168.50.4#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "zookeeper-#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
      node.vm.hostname = "zookeeper-#{i}"
    end
  end
end

