Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ansible"
  config.vm.define "ansible"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible"
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
